/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AccommodationsRouteImport } from './routes/accommodations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiningIndexRouteImport } from './routes/dining/index'
import { Route as DiningMenuRouteImport } from './routes/dining/menu'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsRoute = AccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningIndexRoute = DiningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiningRoute,
} as any)
const DiningMenuRoute = DiningMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DiningRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/activities': typeof ActivitiesRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/reservation': typeof ReservationRoute
  '/dining/menu': typeof DiningMenuRoute
  '/dining/': typeof DiningIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/activities': typeof ActivitiesRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservation': typeof ReservationRoute
  '/dining/menu': typeof DiningMenuRoute
  '/dining': typeof DiningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/activities': typeof ActivitiesRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/reservation': typeof ReservationRoute
  '/dining/menu': typeof DiningMenuRoute
  '/dining/': typeof DiningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodations'
    | '/activities'
    | '/amenities'
    | '/contact'
    | '/dining'
    | '/gallery'
    | '/reservation'
    | '/dining/menu'
    | '/dining/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodations'
    | '/activities'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/reservation'
    | '/dining/menu'
    | '/dining'
  id:
    | '__root__'
    | '/'
    | '/accommodations'
    | '/activities'
    | '/amenities'
    | '/contact'
    | '/dining'
    | '/gallery'
    | '/reservation'
    | '/dining/menu'
    | '/dining/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationsRoute: typeof AccommodationsRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ReservationRoute: typeof ReservationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations': {
      id: '/accommodations'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining/': {
      id: '/dining/'
      path: '/'
      fullPath: '/dining/'
      preLoaderRoute: typeof DiningIndexRouteImport
      parentRoute: typeof DiningRoute
    }
    '/dining/menu': {
      id: '/dining/menu'
      path: '/menu'
      fullPath: '/dining/menu'
      preLoaderRoute: typeof DiningMenuRouteImport
      parentRoute: typeof DiningRoute
    }
  }
}

interface DiningRouteChildren {
  DiningMenuRoute: typeof DiningMenuRoute
  DiningIndexRoute: typeof DiningIndexRoute
}

const DiningRouteChildren: DiningRouteChildren = {
  DiningMenuRoute: DiningMenuRoute,
  DiningIndexRoute: DiningIndexRoute,
}

const DiningRouteWithChildren =
  DiningRoute._addFileChildren(DiningRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationsRoute: AccommodationsRoute,
  ActivitiesRoute: ActivitiesRoute,
  AmenitiesRoute: AmenitiesRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ReservationRoute: ReservationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
